controller_list:
  - name: fake_sting_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_lateral
      - sholder_vertical
      - elbow
      - lower_arm_yaw
      - lower_arm_vertical
      - gripper_yaw
  - name: fake_sting_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - left_finger_joint
initial:  # Define initial robot poses per group
  - group: sting_arm
    pose: default